name: MaxiCity
main: net.reikeb.maxicity.MaxiCity
version: 0.1
author: Max094_Reikeb
api-version: 1.17
softdepend: [HolographicDisplays]

commands:
  plugins:
    description: Lists the plugins installed on the server
    aliases: [pl, about, ver, version]
    usage: /plugins
  balance:
    description: Manages a player's balance
    usage: /balance <balance:add:remove:set> <player> [<amount>]
    permission: ee.balance
    permission-message: You do not have permission to execute this command!
  teamchat:
    description: Manages your team chat
    usage: /teamchat
  socialspy:
    description: Allows you to spy on people's commands
    usage: /socialspy
    permission: ee.socialspy
    permission-message: You do not have permission to execute this command!
  holo:
    description: Setups the score hologram
    usage: /holo <create:set:reload:delete>
    permission: ee.hologram
    permission-message: You do not have permission to execute this command!
  mute:
    description: Mutes a player
    usage: /mute <player> [<reason>]
    permission: ee.mute
    permission-message: You do not have permission to execute this command!
  unmute:
    description: Unmutes a player
    usage: /unmute <player>
    permission: ee.unmute
    permission-message: You do not have permission to execute this command!
  mutereason:
    description: Shows the mute reason of a player
    usage: /mutereason <player>
    permission: ee.showmute
    permission-message: You do not have permission to execute this command!
  vanish:
    description: Hides you from other players
    usage: /vanish
    permission: ee.vanish
    permission-message: You do not have permission to execute this command!
  broadcast:
    description: Broadcasts a message
    usage: /broadcast <message>
    permission: ee.broadcast
    permission-message: You do not have permission to execute this command!
  chat:
    description: Changes the chat status
    usage: /chat <on:off>
    permission: ee.chat
    permission-message: You do not have permission to execute this command!
  emeraldreset:
    description: Resets all the emeralds
    usage: /emeraldreset
    permission: ee.reset
    permission-message: You do not have permission to execute this command!
  msg:
    description: Sends a private message to a user
    aliases: [w, tell]
    usage: /<msg:w:tell> <message>
  r:
    description: Replies to a private message
    usage: /r <message>
  city:
    description: Shows the coordinates of the city
    usage: /city
  setcity:
    description: Modifies the location of the city
    usage: /setcity
    permission: ee.city
    permission-message: You do not have permission to execute this command!
  money:
    description: Show your balance
    usage: /money
  stopholo:
    description: Stops hologram from reloading every 5 minutes
    usage: /stopholo
    permission: ee.hologram
    permission-message: You do not have permission to execute this command!
  group:
    description: Manages groups
    usage: /group <add:remove:move> <player> <group>
    permission: ee.group
    permission-message: You do not have permission to execute this command!
  area:
    description: Manages areas
    usage: /area <new:remove:set:add:info> <name> [<owner:coowner>] [<player>]
    permission: ee.area
    permission-message: You do not have permission to execute this command!

permissions:
  ee.balance:
    description: Allows complete management for player's balance
    default: op
  ee.socialspy:
    description: Allows to spy on people's commands
    default: op
  ee.hologram:
    description: Allows complete management of the holograms
    default: op
  ee.mute:
    description: Allows to mute players
    default: op
  ee.unmute:
    description: Allows to unmute players
    default: op
  ee.showmute:
    description: Allows to show the mute reason of a player
    default: op
  ee.vanish:
    description: Allows you to vanish
    default: op
  ee.broadcast:
    description: Allows you to broadcast a global message in chat
    default: op
  ee.chat:
    description: Allows you to manage the chat
    default: op
  ee.reset:
    description: Allows you to reset emerald counts
    default: op
  ee.city:
    description: Allows you to modify the spawn point of the city
    default: op
  ee.chatalways:
    description: Allows you to always chat
    default: op
  ee.group:
    description: Allows you to manage groups
    default: op
  ee.area:
    description: Allows you to manage areas
    default: op
  ee.loc:
    description: Allows you to select locations
    default: op
  ee.*:
    default: false
    children:
      ee.balance: false
      ee.socialspy: false
      ee.hologram: false
      ee.mute: false
      ee.unmute: false
      ee.showmute: false
      ee.vanish: false
      ee.broadcast: false
      ee.chat: false
      ee.reset: false
      ee.city: false
      ee.chatalways: false
      ee.group: false
      ee.area: false
      ee.loc: false
  team.one:
    description: Belong to team one
    default: false
  team.two:
    description: Belong to team two
    default: false
  team.three:
    description: Belong to team three
    default: false
  team.four:
    description: Belong to team four
    default: false
  team.moderator:
    description: Moderator powers
    default: false
  team.admin:
    description: Admin powers
    default: false
  team.*:
    default: false
    children:
      team.one: false
      team.two: false
      team.three: false
      team.four: false
      team.moderator: false
      team.admin: false
