name: MaxiCity
main: net.reikeb.maxicity.MaxiCity
version: 1.0
author: Max094_Reikeb

commands:
  balance:
    description: Manages a player's balance
  teamchat:
    description: Manages your team chat
  socialspy:
    description: Allows you to spy on people's commands
  holo:
    description: Setup the score hologram